import { clsx } from "clsx";
import { twMerge } from "tailwind-merge";
import api from "../services/api";

export function cn(...inputs) {
  return twMerge(clsx(inputs));
}

export async function downloadPdf(url, filename = "document.pdf") {
  const res = await api.get(url, { responseType: "blob" });
  const contentType = res.headers["content-type"] || "";
  if (contentType.includes("json")) {
    const text = await res.data.text();
    let message = "Failed to generate PDF";
    try { message = JSON.parse(text)?.message || message; } catch {}
    throw new Error(message);
  }
  const blobUrl = URL.createObjectURL(res.data);
  const a = document.createElement("a");
  a.href = blobUrl;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(blobUrl);
}

export async function printPdf(url) {
  const res = await api.get(url);
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.open();
  win.document.write(res.data);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 800);
}

export function printElementAsPdf(elementId, title) {
  const el = document.getElementById(elementId);
  if (!el) return;
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(`<html><head><title>${title || "Document"}</title><style>
    *{margin:0;padding:0;box-sizing:border-box;}
    body{font-family:'Poppins','Helvetica Neue',Arial,sans-serif;color:#1e293b;padding:28px;font-size:12px;}
    .brand-banner{background:#0f172a;color:#fff;border-radius:10px;padding:16px 20px;display:flex;justify-content:space-between;align-items:center;margin-bottom:18px;page-break-inside:avoid;}
    .brand-banner .t{font-size:17px;font-weight:700;}
    .brand-banner .t small{display:block;font-size:11px;font-weight:400;color:#94a3b8;margin-top:2px;}
    .brand-banner .doc{font-size:22px;font-weight:800;text-transform:uppercase;color:#00D4AA;letter-spacing:1.5px;}
    .meta{display:flex;gap:28px;flex-wrap:wrap;margin-bottom:16px;}
    .meta .m .k{font-size:9.5px;text-transform:uppercase;letter-spacing:.5px;color:#64748b;}
    .meta .m .v{font-size:12.5px;font-weight:600;margin-top:2px;}
    table{width:100%;border-collapse:collapse;margin-top:8px;}
    th{background:#00D4AA;color:#0f172a;padding:9px 10px;text-align:left;font-size:10.5px;text-transform:uppercase;letter-spacing:.4px;}
    td,th{padding:8px 10px;font-size:12px;}
    td{border-bottom:1px solid #eef2f7;}
    th:first-child{border-radius:6px 0 0 0;} th:last-child{border-radius:0 6px 0 0;}
    tbody tr:nth-child(even){background:#fafcfe;}
    .num{text-align:right;}
    .footer{position:fixed;bottom:0;left:0;right:0;text-align:center;font-size:10px;color:#94a3b8;padding:10px;border-top:1px solid #e2e8f0;}
  </style></head><body>
    <div class="brand-banner"><div class="t">M-TAI Report<small>Generated: ${new Date().toLocaleString()}</small></div><div class="doc">${(title || "Document").replace(/<[^>]+>/g, '').toUpperCase()}</div></div>
    <div id="copy"></div>
    <div class="footer">Generated by M-TAI · This is a system-generated report</div>
    <script>document.addEventListener('DOMContentLoaded',function(){
      var src=opener.document.getElementById('${elementId}').cloneNode(true);
      src.querySelectorAll('input,select,button,svg,svg *').forEach(function(b){if(b.remove)b.remove()});
      document.getElementById('copy').appendChild(src);
      setTimeout(function(){window.print()},700); });
    <\/script>
  </body></html>`);
  win.document.close();
}
